### ISSUE TITLE
Feed::from_str returns Result<Feed, &'static str>

### ISSUE THREAD

**Issue by kpcyrd** [vtduncan/rust-atom#9]
hey, I'm wrapping around this library and I've noticed rust-atom doesn't define it's own Error Type but instead returns &str in case of an error.

Usually I'd `impl From<otherlib::Error> for MyError` but this is only possible if there's a specific Error Type I can use :)

Could you add one and use that instead of a plain string?

**Comment by vtduncan** [comment]
Hi @kpcyrd! Thank you for reporting this. I'm sorry that the errors are strings right now. Having an error type would definitely be an improvement!

I haven't been maintaining this library in a while, but if you wanted to make this change then it would be very welcome.

**Comment by vtduncan** [comment]
Merged!
